blocks:
 - 35:1=3:Orange Wool - Its Orange!
 - 35:2=2:Magenta Wool - Another color that hurts my eye.
overplaced: 'You already reached max blocks count'
usedefault: true
useplayerLimits: false
canseelimits: false
canseeplaced: false